<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="docs\api\" />
      <Folder Include="docs\architechture\" />
      <Folder Include="docs\database\" />
      <Folder Include="docs\uml\" />
    </ItemGroup>

</Project>
